### ISSUE TITLE
Oscillations with semilag advection 

### ISSUE THREAD

**Issue by JFLemieux73** [McGill-sea-ice/1D-SIM#5]
![Fig_block_ice](https://user-images.githubusercontent.com/31927797/98564291-2cecc100-227a-11eb-8ad9-9eb28254902a.png)

**Comment by JFLemieux73** [comment]
These oscillations grow at the beginning and then are quite 'stable'. The value of Delta t  does not affect this results. 1440 time levels with dt=600 s.

**Comment by JFLemieux73** [comment]
![Fig_block_ice_b](https://user-images.githubusercontent.com/31927797/98581870-1c474580-2290-11eb-8a8c-fd2a58b072af.png)

Jai parlé à Pierre. Ces 'oscillations' sont probablement causées par la cond initiale difficile. Dans la 2e fig, upwind est utilisé pour les 720 premier dt et ensuite c'est semilag.

**Comment by JFLemieux73** [comment]
Le problème peut probablement être réglé en ajoutant des limiteurs aux calc de hbef et Abef. Cas simple avec hn2in(i-1)=hn2in(i)=1 et hn2in(i+1)=0. hbef = hn2in(i) - ( hn2in(i+1) - hn2in(i-1) )*alpham / Deltax...hbef=1-(0-1)*alpham/Deltax

hbef=1+alpham/Deltax...ca fait que hbef au bord est plus grand que 1...ce qui explique le résultat ci-dessus.

**Comment by JFLemieux73** [comment]
Does it mean the order (spatial) of the scheme matters for this issue?

**Comment by JFLemieux73** [comment]
![Fig_block_ice_c](https://user-images.githubusercontent.com/31927797/98597879-a949c900-22a7-11eb-9f2b-aafdab2945ca.png)

With limiter...works quite well.

**Comment by JFLemieux73** [comment]
![Fig_block_ice_f](https://user-images.githubusercontent.com/31927797/98685757-c4fbb080-2335-11eb-9242-2e3408471eb3.png)

2nd order accurate + limiters. 8 day simulations with dt=600 s.

**Comment by pellerinpp** [comment]
SL est moins (ou peu) dispersif

**Comment by JFLemieux73** [comment]
Il fait la job! Je peux améliorer les limiteurs...j,ai pas fait exactement comme dans ton papier.

**Comment by pellerinpp** [comment]
Ok ca serait bien de voir la courbe rouge au départ quand le semi-lag commence son intégration, aussi en augmentant l'ordre des interpolations tu vas pouvoir encore mieux conserver des structures abruptes et complexes, la clé est l'utilisation simultanée d'un schéma de diffusion sélectif avec le semi-lag. De cette manière tu verras que les limiteurs seront moins actifs. Avec les limiteurs actifs tu as un genre de schéma advection-diffusion.

**Comment by JFLemieux73** [comment]
![Fig_block_ice_g](https://user-images.githubusercontent.com/31927797/98718350-54b45580-235c-11eb-8e04-a914f3aa9322.png)

J'ai mis un limiteur plus sophistiqué mais l'impact est faible.

**Comment by pellerinpp** [comment]
Je crois que la forme adoucie par le schéma upwind est facilement solutionnable par le SL (deuxième ordre), c'est toujours le cas ?, les deux schémas ont un ordre équivalent. Et bref le limiteur ne fonctionne peut-être pas bcp. Tu pourrais compter le nombre de fois qu’il est actif et les valeurs min, max et moyenne qu’il contrôle. Aussi tu pourrais avoir un graphique 1-D qui montre les valeurs contrôlées par le limiteur, on verrait son évolution temporelle.

**Comment by JFLemieux73** [comment]
Ok. Je vais regarder aussi ce qui se passe au début de la simulation.

**Comment by JFLemieux73** [comment]
![Fig_block_ice_h](https://user-images.githubusercontent.com/31927797/98734041-6ce1a000-236f-11eb-809f-76e0504b3a5a.png)

Impact ordre du schéma. Ça semble faible pour ce test.

**Comment by JFLemieux73** [comment]
![Fig_block_ice_i](https://user-images.githubusercontent.com/31927797/98735198-fe054680-2370-11eb-8cf0-ef84f75eebc8.png)

4 premiers jours avec upwind, switch ensuite pour SL. 
SL maintient la forme crée par upwind. (il semble y avoir encore de la diffusion avec SL mais c'est faible).

**Comment by JFLemieux73** [comment]
Pour comprendre l'effet des limiteurs on peut simplifier le problème: ordre 1 et on met le "forçage" fm=hdu/dx=0.

![Fig_block_ice_j](https://user-images.githubusercontent.com/31927797/98818334-6861c980-23f9-11eb-8c19-50d3a80a0afa.png)
